/**
 * watch-targets.json — persistent registry of folders the daemon
 * watches for auto-re-ingest.
 *
 * Each entry: { workspace, root, registered_at }. `folklore this`
 * registers the cwd; the daemon reads the file on boot and starts a
 * chokidar watcher per root.
 *
 * Single-writer, multi-reader. Registration is idempotent — adding
 * the same (workspace, root) twice updates the timestamp instead of
 * duplicating the row.
 *
 * V5 schema note: the entry field was renamed `room` → `workspace`,
 * changing the on-disk watch-targets.json shape. This is local state
 * regenerated by `folklore this`, so no migration shim is provided —
 * a stale file with the old `room` field simply yields no usable
 * targets until `folklore this` re-registers them.
 */

import { existsSync, readFileSync } from 'node:fs';
import { atomicWriteSync } from './atomic-write.js';

export interface WatchTarget {
  readonly workspace: string;
  readonly root: string;
  readonly registered_at: string;     // ISO-8601
  /**
   * Last time the daemon walked this root for catch-up. The daemon
   * updates this on boot after reconciling files modified during
   * its downtime. Absent on freshly-registered targets — first boot
   * after registration walks everything.
   */
  readonly last_scan_at?: string;
}

interface WatchTargetsFile {
  readonly version: 1;
  readonly targets: readonly WatchTarget[];
}

const empty = (): WatchTargetsFile => ({ version: 1, targets: [] });

const safeRead = (path: string): WatchTargetsFile => {
  if (!existsSync(path)) return empty();
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as WatchTargetsFile;
    if (parsed.version !== 1 || !Array.isArray(parsed.targets)) return empty();
    return parsed;
  } catch {
    return empty();
  }
};

const safeWrite = (path: string, file: WatchTargetsFile): void => {
  // tmp+rename so a crash mid-write never loses the registered
  // watch-targets — losing them means every `folklore this` has
  // to be re-run.
  atomicWriteSync(path, JSON.stringify(file, null, 2));
};

export const loadWatchTargets = (path: string): readonly WatchTarget[] =>
  safeRead(path).targets;

/**
 * Idempotent register. Replaces any existing row with the same
 * (workspace, root) pair so re-running `folklore this` refreshes the
 * registered_at timestamp without duplicating the entry.
 */
export const registerWatchTarget = (
  path: string,
  target: Omit<WatchTarget, 'registered_at'>,
  now: Date = new Date(),
): readonly WatchTarget[] => {
  const file = safeRead(path);
  const filtered = file.targets.filter(
    (t) => !(t.workspace === target.workspace && t.root === target.root),
  );
  const next: readonly WatchTarget[] = [
    ...filtered,
    { ...target, registered_at: now.toISOString() },
  ];
  safeWrite(path, { version: 1, targets: next });
  return next;
};

export const unregisterWatchTarget = (
  path: string,
  target: { readonly workspace: string; readonly root: string },
): readonly WatchTarget[] => {
  const file = safeRead(path);
  const next = file.targets.filter(
    (t) => !(t.workspace === target.workspace && t.root === target.root),
  );
  safeWrite(path, { version: 1, targets: next });
  return next;
};

/**
 * Mutate `last_scan_at` for one target. Called by the daemon
 * file-watcher after a boot-time catch-up scan completes — the
 * stamp is what closes the file-events-lost-during-daemon-downtime
 * window flagged in code review.
 */
export const stampWatchTargetScan = (
  path: string,
  target: { readonly workspace: string; readonly root: string },
  now: Date = new Date(),
): readonly WatchTarget[] => {
  const file = safeRead(path);
  const next = file.targets.map((t) =>
    t.workspace === target.workspace && t.root === target.root
      ? { ...t, last_scan_at: now.toISOString() }
      : t,
  );
  safeWrite(path, { version: 1, targets: next });
  return next;
};
